### GET comments
GET http://localhost:3000/comments


### GET comments by id 
GET http://localhost:3000/comments/6877d2a703d6fc0e2b5d1588

### POST CREATE COMMENT

POST http://localhost:3000/comments
Content-Type: application/json

{
    "product_id": "686bfa2f7531bca8d4ccf11d",
    "comment": "awesome product",
    "liked": true,
    "star": 5
}

###
POST http://localhost:3000/comments
Content-Type: application/json

{
    "product_id": "686bfa2f7531bca8d4ccf11d",
    "comment": "give me back money bit**",
    "liked": false,
    "star": 1
}

###  PUT - UPDATE COMMENT
PUT http://localhost:3000/comments/6877d2a703d6fc0e2b5d1588
Content-Type: application/json

{
    "product_id": "686bfa2f7531bca8d4ccf11d",
    "comment": "Thanks, I liked a lot , good quality.",
    "liked": true,
    "star": 4
}

###  DELETE - delete comment
DELETE http://localhost:3000/comments/6876933b49cce121f7be8a9d
Content-Type: application/json

{

}