### GET inventories
GET http://localhost:3000/inventory

### GET inventory by id
GET http://localhost:3000/inventory/686ebfb08ec6bb4b062a5b41

### CREATE Inventory

POST http://localhost:3000/inventory
Content-Type: application/json

{
  "product_id": "6882926c4a7c06ba7396ff63",
  "type": ["MEN"],
  "categorie": ["SPORT"],
  "color": ["WHITE"],
  "size": ["S"],
  "units_available": 400,
  "cost_per_unit": 50
}
### CREATE Inventory

POST http://localhost:3000/inventory
Content-Type: application/json

{
  "product_id": "6882926c4a7c06ba7396ff63",
  "type": ["MEN"],
  "categorie": ["SPORT"],
  "color": ["WHITE"],
  "size": ["S"],
  "units_available": 100,
  "cost_per_unit": 20
}

### CREATE Inventory

POST http://localhost:3000/inventory
Content-Type: application/json

{
  "product_id": "68828e6023c300c55715493e",
  "type": ["MEN"],
  "categorie": ["SPORT"],
  "color": ["WHITE"],
  "size": ["S"],
  "units_available": 50,
  "cost_per_unit": 10
}



### UPDATE Inventory

PUT http://localhost:3000/inventory/6883b1a3458ba2bb1dc28833
Content-Type: application/json

{
  "product_id":"6882926c4a7c06ba7396ff63"
}

### UPDATE Inventory

DELETE http://localhost:3000/inventory/6883b1a3458ba2bb1dc28833
Content-Type: application/json

{

}