### GET inventories
GET http://localhost:3000/inventory

### GET inventory by id
GET http://localhost:3000/inventory/686ebf0a8ec6bb4b062a5b33

### CREATE Inventory

POST http://localhost:3000/inventory
Content-Type: application/json

{
  "product_id": "686bf9af6eabe4eb3cc04491",
  "type": ["WOMEN"],
  "categorie": ["SPORT"],
  "color": ["WHITE"],
  "size": ["S"],
  "units_available": 200,
  "cost_per_unit": 42,
  "units_sold": 2
}

### UPDATE Inventory

PUT http://localhost:3000/inventory/686ebfb08ec6bb4b062a5b41
Content-Type: application/json

{
  "product_id":"686bf91ad217b8c026f3ace6",
  "type": ["MEN"],
  "categorie": ["CASUAL"],
  "color": ["RED"],
  "size": ["Large"],
  "units_available": 400,
  "cost_per_unit": 40,
  "units_sold": 3
}

### UPDATE Inventory

DELETE http://localhost:3000/inventory/68700c30e622231ff799f622
Content-Type: application/json

{

}