### GET PRODUCTS

GET http://localhost:3000/products

### GET PRODUCT BY ID

GET http://localhost:3000/products/686bf8fbd217b8c026f3ace3

### GET PRODUCT BY ID
GET http://localhost:3000/products/686bf9af6eabe4eb3cc04491

###
GET http://localhost:3000/products/6882928e32bb62865323fccd

### CREATE PRODUCT

POST http://localhost:3000/products
Content-Type: application/json

{
  "title":"product 10",
  "short_description":"short description 10",
  "price": 500,
  "reference":"SHIRT300" 
}

### UPDATE PRODUCT

PUT http://localhost:3000/products/6882928e32bb62865323fccd
Content-Type: application/json

{
  "title":"product 10",
  "short_description":"update short description 10",
  "price": 800,
  "reference":"SHIRT660" 
}

### DELETE PRODUCT

DELETE http://localhost:3000/products/6882928e32bb62865323fccd
Content-Type: application/json

{
  
}