
### GET Users
GET http://localhost:3000/users

### GET User
GET http://localhost:3000/users/68828304f760b32f24a12b41


### Create user
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "username":"andres", 
  "email":"andres@gmail.com", 
  "phone":"123456789",
  "address":"AUT 5", 
  "password":"123456789"
}

### Create user
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "username":"superuser", 
  "email":"superuser@gmail.com", 
  "phone":"1234567890",
  "address":"CR 5", 
  "password":"1234567890"
}

### Login user
POST http://localhost:3000/users/login/
Content-Type: application/json

{
  "email":"superuser@gmail.com", 
  "password":"123"
}

### Update user
PUT http://localhost:3000/users/update/68828311f760b32f24a12b44
Content-Type: application/json

{
  "address":"CR 555555555"
}

### Update user password
PUT http://localhost:3000/users/update-password/68828311f760b32f24a12b44
Content-Type: application/json

{
  "newPassword":"123", 
  "repetedPassword":"123", 
  "oldPassword":"1234567890"
}


### Logout user
POST http://localhost:3000/users/logout
Content-Type: application/json

{
  "email":"cristian@gmail.com", 
  "password":"123456789"
}


### delete user
DELETE http://localhost:3000/users/delete/68828304f760b32f24a12b41
Content-Type: application/json

{
  
}
